[package]
name = "synapce"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.26"
crossterm = "0.27"
rodio = "0.17"
symphonia = "0.5"
lofty = "0.18"
tokio = { version = "1", features = ["full"] }
